# Generated by Django 5.1.4 on 2025-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_tag_order_book_order_customer_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='bookstore.tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('Romance', 'Romance'), ('technelogy', 'technelogy'), ('Fiction', 'Fiction')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('out of order', 'out of order'), ('in progress', 'in progress')], max_length=200, null=True),
        ),
    ]
