# Generated by Django 5.1.4 on 2025-01-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_tags_alter_book_category_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Mystery', 'Mystery'), ('technelogy', 'technelogy'), ('Fiction', 'Fiction')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('in progress', 'in progress'), ('out of order', 'out of order')], max_length=200, null=True),
        ),
    ]
