# Generated by Django 5.1.4 on 2025-01-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_customer_user_alter_book_category_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=190, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('technelogy', 'technelogy'), ('Romance', 'Romance'), ('Fiction', 'Fiction')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('out of order', 'out of order'), ('in progress', 'in progress')], max_length=200, null=True),
        ),
    ]
