# Generated by Django 5.1.4 on 2025-01-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_customer_avatar_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('technelogy', 'technelogy')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=190, default='profile.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('out of order', 'out of order'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('in progress', 'in progress')], max_length=200, null=True),
        ),
    ]
